// Local-only QA proxy. Never included in the application bundle.
import http from "node:http";

const page = String.raw`<!doctype html><meta charset="utf-8"><title>Portfolio motion audit</title>
<style>body{margin:0;background:#060a0e}iframe{position:fixed;inset:0;width:100%;height:100%;border:0}aside{position:fixed;z-index:9;right:8px;top:8px;width:260px;background:#09121fee;color:#d6e9fa;padding:12px;font:12px monospace;border:1px solid #597387}button,input{font:inherit;padding:7px;margin:3px}pre{white-space:pre-wrap;max-height:70vh;overflow:auto}#toggle{position:fixed;z-index:10;right:8px;bottom:8px}aside.hidden{display:none}</style>
<iframe id="site" src="/?motion-audit=1#home" title="Portfolio production preview"></iframe>
<button id="toggle">Audit panel</button><aside id="panel"><label>Page Y <input id="y" type="number" value="0" style="width:90px"></label><button id="jump">Jump</button><button id="profile">Profile all boundaries</button><button id="inspect">Inspect</button><button id="motion">Toggle reduced motion</button><button id="touch">Toggle coarse input</button><button id="hidden">Toggle visibility</button><pre id="result">Ready</pre></aside>
<script>
const frame=document.querySelector('#site'), output=document.querySelector('#result');
for(const [id,label] of [['sweep','Boundary regression'],['graphics','Count graphics'],['sections','Section regression']]){const button=document.createElement('button');button.id=id;button.textContent=label;output.before(button);}
let reduced=false,touch=false,hidden=false,lastResults=[];
const w=()=>{const win=frame.contentWindow;if(win.__motionAudit)win.gsap=win.__motionAudit.gsap;return win;};
frame.onload=()=>{w().gsap=w().__motionAudit?.gsap;};
const read=()=>{const win=w(),doc=win.document,gsap=win.gsap,st=gsap?.core.globals().ScrollTrigger;return {viewport:[win.innerWidth,win.innerHeight],scrollY:win.scrollY,overflow:doc.documentElement.scrollWidth-win.innerWidth,triggers:st?.getAll().length,gsap:!!gsap,activeProjects:gsap?Array.from(new Set(gsap.globalTimeline.getChildren(true,true,false).filter(t=>t.isActive()).flatMap(t=>t.targets().map(el=>el.closest?.('[data-work-project]')?.dataset.workProject).filter(Boolean)))):[],promoted:Array.from(doc.querySelectorAll('*')).filter(el=>win.getComputedStyle(el).willChange!=='auto').length,canvases:Array.from(doc.querySelectorAll('canvas')).map(el=>({width:el.width,height:el.height})),handoffs:Array.from(doc.querySelectorAll('[data-work-handoff]')).map(el=>({i:el.dataset.workHandoff,top:el.getBoundingClientRect().top+win.scrollY,height:el.getBoundingClientRect().height})),links:Array.from(doc.querySelectorAll('a')).map(el=>({text:el.textContent.trim(),href:el.getAttribute('href')}))};};
document.querySelector('#toggle').onclick=()=>document.querySelector('#panel').classList.toggle('hidden');
document.querySelector('#jump').onclick=()=>{w().scrollTo({top:Number(document.querySelector('#y').value),behavior:'instant'});w().gsap?.core.globals().ScrollTrigger?.update();output.textContent=JSON.stringify(read(),null,2);};
document.querySelector('#inspect').onclick=()=>output.textContent=JSON.stringify(read(),null,2);
document.querySelector('#motion').onclick=()=>{reduced=!reduced;w().__setMotionPolicy({reduced,touch});output.textContent='Reduced motion simulated: '+reduced;};
document.querySelector('#touch').onclick=()=>{touch=!touch;w().__setMotionPolicy({reduced,touch});output.textContent='Coarse input simulated: '+touch;};
document.querySelector('#hidden').onclick=()=>{hidden=!hidden;Object.defineProperty(w().document,'visibilityState',{configurable:true,get:()=>hidden?'hidden':'visible'});w().document.dispatchEvent(new Event('visibilitychange'));output.textContent='Hidden simulated: '+hidden;};
document.querySelector('#sweep').onclick=async()=>{const win=w(),doc=win.document,st=win.__motionAudit.ScrollTrigger,results=[];for(const el of doc.querySelectorAll('[data-work-handoff]')){const trigger=st.getAll().find(t=>t.trigger===el);if(!trigger){results.push({boundary:el.dataset.workHandoff,editorial:true});continue;}for(const progress of [0,.25,.5,.75,1,.5,0,1]){win.scrollTo({top:trigger.start+(trigger.end-trigger.start)*progress,behavior:'instant'});st.update();await new Promise(r=>win.requestAnimationFrame(()=>win.requestAnimationFrame(r)));const worlds=Array.from(el.querySelectorAll('[data-handoff-outgoing],[data-handoff-incoming]')).map(world=>{const rect=world.getBoundingClientRect();return {x:win.gsap.getProperty(world,'xPercent'),opacity:Number(win.getComputedStyle(world).opacity),intersects:rect.right>0&&rect.left<win.innerWidth&&rect.bottom>0&&rect.top<win.innerHeight};});const label=doc.querySelector('[data-work-active-label]')?.textContent;results.push({boundary:el.dataset.workHandoff,progress,visualProgress:trigger.animation.progress(),worlds,label,blank:!worlds.some(world=>world.intersects&&world.opacity>.05),overflow:doc.documentElement.scrollWidth-win.innerWidth});}}output.textContent=JSON.stringify(results,null,2);};
document.querySelector('#graphics').onclick=async()=>{const win=w(),gl=win.WebGL2RenderingContext.prototype,ctx=win.CanvasRenderingContext2D.prototype;const draw=gl.drawArrays,elements=gl.drawElements,clear=ctx.clearRect;let draws=0,clears=0;gl.drawArrays=function(...args){draws++;return draw.apply(this,args)};gl.drawElements=function(...args){draws++;return elements.apply(this,args)};ctx.clearRect=function(...args){clears++;return clear.apply(this,args)};await new Promise(r=>win.setTimeout(r,600));gl.drawArrays=draw;gl.drawElements=elements;ctx.clearRect=clear;output.textContent=JSON.stringify({scrollY:win.scrollY,visibility:win.document.visibilityState,heroDraws:draws,gridClears:clears,heroActive:win.document.querySelector('#home').dataset.sceneActive,ms:600});};
document.querySelector('#sections').onclick=async()=>{const win=w(),doc=win.document,st=win.__motionAudit.ScrollTrigger,results=[];const regions=[...doc.querySelectorAll('[data-work-project]'),doc.querySelector('#home'),doc.querySelector('#lab'),doc.querySelector('#about'),doc.querySelector('#contact'),doc.querySelector('footer')];for(const el of regions){const top=el.getBoundingClientRect().top+win.scrollY;const steps=el.id==='home'||el.id==='about'||el.id==='contact'?[.1,.3,.5,.7,.9]:[.1,.5,.9];for(const progress of steps){const story=el.querySelector('[data-motion="active"]');const max=story?story.offsetHeight-story.firstElementChild.offsetHeight:Math.max(0,el.offsetHeight-win.innerHeight);win.scrollTo({top:top+max*progress,behavior:'instant'});st.update();await new Promise(r=>win.requestAnimationFrame(()=>win.requestAnimationFrame(r)));results.push({section:el.id||el.dataset.workProject||'footer',progress,overflow:doc.documentElement.scrollWidth-win.innerWidth,triggerMismatch:st.getAll().filter(t=>t.isActive&&t.animation&&t.vars.scrub===true&&Math.abs(t.progress-t.animation.progress())>.01).length,invisibleLinks:Array.from(el.querySelectorAll('a')).filter(a=>{const rect=a.getBoundingClientRect();if(rect.height===0||win.getComputedStyle(a).visibility==='hidden')return false;let node=a;while(node&&node!==el){if(Number(win.getComputedStyle(node).opacity)<.02)return true;node=node.parentElement;}return false;}).map(a=>a.getAttribute('href'))});}}output.textContent=JSON.stringify(results,null,2);};
document.querySelector('#profile').onclick=async()=>{const win=w(),doc=win.document;lastResults=[];let draws=0,clears=0;const gl=win.WebGL2RenderingContext?.prototype,ctx=win.CanvasRenderingContext2D.prototype;const originalDraw=gl?.drawArrays,originalElements=gl?.drawElements,originalClear=ctx.clearRect;if(gl){gl.drawArrays=function(...args){draws++;return originalDraw.apply(this,args)};gl.drawElements=function(...args){draws++;return originalElements.apply(this,args)}}ctx.clearRect=function(...args){clears++;return originalClear.apply(this,args)};
try{for(const el of doc.querySelectorAll('[data-work-handoff]')){const top=el.getBoundingClientRect().top+win.scrollY,height=el.getBoundingClientRect().height-win.innerHeight;win.scrollTo({top:top-120,behavior:'instant'});win.gsap?.core.globals().ScrollTrigger?.update();await new Promise(r=>win.setTimeout(r,250));const intervals=[],longTasks=[];let observer;try{observer=new win.PerformanceObserver(list=>longTasks.push(...list.getEntries().map(e=>e.duration)));observer.observe({type:'longtask'});}catch{}draws=0;clears=0;let previous=0,count=0;const states=[];await new Promise(resolve=>{const tick=(now)=>{if(previous)intervals.push(now-previous);previous=now;const phase=count/100;const position=phase<.45?phase/.45:phase<.7?1-(phase-.45)/.25:(phase-.7)/.3;win.dispatchEvent(new win.WheelEvent('wheel',{deltaY:(top+position*height-win.scrollY),bubbles:true,cancelable:true}));if(count%25===0)states.push(read().activeProjects);if(++count<=100)win.requestAnimationFrame(tick);else resolve();};win.requestAnimationFrame(tick)});observer?.disconnect();intervals.sort((a,b)=>a-b);lastResults.push({boundary:el.dataset.workHandoff,frames:intervals.length,median:intervals[Math.floor(intervals.length*.5)],p95:intervals[Math.floor(intervals.length*.95)],max:intervals.at(-1),over33ms:intervals.filter(n=>n>33).length,longTasks,heroDraws:draws,gridClears:clears,activeProjects:states});output.textContent=JSON.stringify(lastResults,null,2);}}finally{if(gl){gl.drawArrays=originalDraw;gl.drawElements=originalElements}ctx.clearRect=originalClear;}};
</script>`;

// Simulate capability media queries before application code subscribes. CSS and
// JS branches change together; these switches never alter the host OS settings.
const bootstrap = String.raw`<script>
(() => { const native=window.matchMedia.bind(window), lists=[]; let reduced=false,touch=false;
const getter=Object.getOwnPropertyDescriptor(MediaQueryList.prototype,'matches').get;
window.matchMedia=(query)=>{const list=native(query);Object.defineProperty(list,'matches',{get:()=>{if(query.includes('prefers-reduced-motion')){if(query.includes('no-preference')&&reduced)return false;if(query.includes(': reduce')||query.includes(':reduce'))return reduced;}if(touch&&(query.includes('pointer: fine')||query.includes('hover: hover')))return false;if(touch&&(query.includes('pointer: coarse')||query.includes('hover: none')))return true;return getter.call(list);}});lists.push(list);return list;};
window.__setMotionPolicy=(policy)=>{reduced=policy.reduced;touch=policy.touch;let style=document.querySelector('#audit-media');if(!style){style=document.createElement('style');style.id='audit-media';document.head.append(style);}let css='';const collect=rules=>{for(const rule of rules){if(rule.conditionText?.includes('prefers-reduced-motion: reduce')&&reduced)css+=rule.cssText.replaceAll('(prefers-reduced-motion: reduce)','(min-width: 0px)');else if(rule.cssRules)collect(rule.cssRules);}};for(const sheet of document.styleSheets){if(sheet.ownerNode===style)continue;try{collect(sheet.cssRules);}catch{}}style.textContent=css;for(const list of lists)list.dispatchEvent(new Event('change'));window.dispatchEvent(new Event('resize'));window.__motionAudit?.gsap.matchMediaRefresh();};})();
</script>`;

http.createServer((request, response) => {
  if (request.url === "/__motion-audit") {
    response.writeHead(200, { "Content-Type": "text/html" });
    response.end(page);
    return;
  }
  const upstream = http.request({ hostname: "127.0.0.1", port: 3000, path: request.url, method: request.method, headers: { ...request.headers, host: "127.0.0.1:3000", "accept-encoding": "identity" } }, (incoming) => {
    if (request.url.includes("motion-audit=1") && incoming.headers["content-type"]?.includes("text/html")) {
      const chunks = [];
      incoming.on("data", (chunk) => chunks.push(chunk));
      incoming.on("end", () => {
        const headers = { ...incoming.headers };
        delete headers["content-length"];
        response.writeHead(incoming.statusCode, headers);
        response.end(Buffer.concat(chunks).toString().replace("<head>", "<head>" + bootstrap));
      });
    } else {
      response.writeHead(incoming.statusCode, incoming.headers);
      incoming.pipe(response);
    }
  });
  upstream.on("error", () => { response.writeHead(502); response.end("Start the production preview on port 3000 first."); });
  request.pipe(upstream);
}).listen(3001, "127.0.0.1", () => console.log("Local QA: http://127.0.0.1:3001/__motion-audit"));
